### ISSUE TITLE
The bash commands to train GAN model

### ISSUE THREAD

**Issue by TrinhQuocNguyen** [ewigspace1910/ReID_maket1501#3]
Good morning.
Thank you for your great work.
Can you confirm where is the path in your guide?
TRAIN_IMG_DIR="../../datasets/ReidGan/duke2mark/train"

Thanks

**Comment by TrinhQuocNguyen** [comment]
Also, your work is great, can you please share your paper file for reference?
Thanks

**Comment by hoahoa1808** [comment]
@TrinhQuocNguyen  It should be "../../datasets/4Gan/duke2mark/train"
Maybe... I made a mistake when I was writing so long rm file lol

**Comment by TrinhQuocNguyen** [comment]
@hoahoa1808 
Thank you very much. I modified it myself and the command for the first stage (pre-training) can be executed.
Thanks
