### ISSUE TITLE
Error when running the command of fine tuning 

### ISSUE THREAD

**Issue by TrinhQuocNguyen** [ewigspace1910/ReID_maket1501#4]
Thank you for your great worK!

Do you have any ideas of this error?
target_features shape torch.Size([12936])
Traceback (most recent call last):
  File "_target_finetune.py", line 167, in gen_psuedo_labels
    rerank_dist = compute_jaccard_distance(cluster_features, print_flag=True, search_option=5) #for DBSCAN
  File "DAPRH/DAPRH/modules/utils/faiss_rerank.py", line 57, in compute_jaccard_distance
    index.add(target_features.cpu().numpy())
  File "/home/***/anaconda3/envs/py38/lib/python3.8/site-packages/faiss/__init__.py", line 213, in replacement_add
    n, d = x.shape
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_target_finetune.py", line 485, in <module>
    main()
  File "_target_finetune.py", line 128, in main
    main_worker(args)
  File "_target_finetune.py", line 290, in main_worker
    tmp_dataset, num_clusters,  ce_scores, cep_scores = gen_psuedo_labels(target_dataset=dataset_target, 
  File "_target_finetune.py", line 170, in gen_psuedo_labels
    rerank_dist = compute_jaccard_distance(cluster_features, print_flag=True, search_option=1) #for DBSCAN
  File "DAPRH/DAPRH/modules/utils/faiss_rerank.py", line 45, in compute_jaccard_distance
    index.add(target_features.cpu().numpy())
  File "/home/***/anaconda3/envs/py38/lib/python3.8/site-packages/faiss/__init__.py", line 213, in replacement_add
    n, d = x.shape
ValueError: not enough values to unpack (expected 2, got 1)

Thank you.

**Comment by TrinhQuocNguyen** [comment]
@hoahoa1808 
Good morning.
Do you have any ideas on how to fix this error?
Thanks

**Comment by hoahoa1808** [comment]
Hi @ewigspace1910, Please check the code in main branch. Thanks

**Comment by ghost** [comment]
> @hoahoa1808 Good morning. Do you have any ideas on how to fix this error? Thanks

Hi @TrinhQuocNguyen, Sorry for late response.
For your issue, I thought you are using our unofficial code which includes  a few  syntax and logic errors. Hence I just updated newest code of this project. Please pull it and run. No change in setup.
btw why did u set option to 5 and  1?
```rerank_dist = compute_jaccard_distance(cluster_features, print_flag=True, search_option=5) ```

We currently set them to 2/0 as best option for optimizing gpu memory/ram

**Comment by TrinhQuocNguyen** [comment]
Dear @ewigspace1910 

Thank you for your great work and support.
I somehow made it run. Yatta! 

There are some points I have modified, hope it helps you improve the repo:
- "data" and "datasets" folders are confusing. I think you meant "data"
- solver.py: 
  Line 330: is this "log_dir" -> "sample_dir"?
  Line 512: is this "log_dir" -> "sample_dir"?
  Line 615: I commented it "if random.uniform(0, 1) >= self.prob: continue".  

Also, could you please share the pdf file of your paper? 
I am really interested in your work.

Thank you.

**Comment by ghost** [comment]
> Dear @ewigspace1910
> 
> Thank you for your great work and support. I somehow made it run. Yatta!
> 
> There are some points I have modified, hope it helps you improve the repo:
> 
> * "data" and "datasets" folders are confusing. I think you meant "data"
> * solver.py:
>   Line 330: is this "log_dir" -> "sample_dir"?
>   Line 512: is this "log_dir" -> "sample_dir"?
>   Line 615: I commented it "if random.uniform(0, 1) >= self.prob: continue".
> 
> Also, could you please share the pdf file of your paper? I am really interested in your work.
> 
> Thank you.


Thank you for your constructive recommendations. We will consider these for our next projects.
To access our paper, please contact us at ducanh.ng@vnu.edu.vn
btw, I will close the issue in next few days if there is no error occurring in your code. 
Regards!

**Comment by TrinhQuocNguyen** [comment]
@ewigspace1910 
Thank you for your support.
